### ISSUE TITLE
Potentially useful prior art

### ISSUE THREAD

**Issue by daguar** [geocode-city/api#2]
Hello! Saw this pop across my notifications and while there's not enough info for me to know the scope exactly, when I see "geocode" and "city" I figure maybe worth sharing something.

1. Pelias ( https://github.com/pelias/pelias ) is an Elasticsearch-based geocoder that I have seen used with local gazetteers like NYC address data.

2. Nominatim ( https://nominatim.org/ ) is the OpenStreetMap geocoder.

Entirely possible none of this is relevant, but I'm curious what you're up to with this and figured I'd share a couple things in case they're interesting! Feel free to close out.

**Comment by lfborjas** [comment]
Hi Dave, dude, good to hear from you; thanks for the links! Also, clicking around the Pelias project, found this, which I think is very close in scope/features to what I want here: https://github.com/pelias/placeholder

It's more of a toy project to support another toy project: I use the free tier of Algolia Places for the city autocomplete field in [freenatalchart.xyz](https://freenatalchart.xyz), but they recently announced [they'll be retiring Places in 2022](https://www.algolia.com/blog/sunseting-our-places-feature/), so I figured I could put in some hours to build an equivalent thing, focused on cities, vs. the more advanced -- and paid -- options out there. Definitely happy to go with either of the linked options though, I just didn't want to pay for e.g. google's version if I could duck-tape something together, and learn along the way 😅
